services:
  - type: web
    name: log-auto-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn log_manager.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: #k75&$*kr&7=-gpyr=-_d(gr8wp(9*_(@lni*t7#wjn%6*#clt
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "value: "logauto2.onrender.com,localhost,127.0.0.1"
